title: "Bradley Ryan | Blue Team Portfolio"
description: "Cybersecurity Analyst | Threat Hunting | SIEM | Detection Engineering"
theme: jekyll-theme-cayman
show_downloads: false
google_analytics: false
github:
  is_project_page: false
  is_user_page: true

# Optional navbar links
navbar-links:
  Home: /
  Projects: /projects/

